### ISSUE TITLE
Crash when loading solution with a build.fsx at the root

### ISSUE THREAD

**Issue by baronfel** [georgewfraser/fsharp-language-server#2]
Hi, I've tried this with a large work project but I can't get IDE features to work when there's a build.fsx in the project root. I get the following stack trace related to being unable to get an assembly version off of a pseudo-project:

```
Listening on stdin
Add workspace root /Users/chethusk/work/server
Creating project options for script build.fsx
Looking for PsuedoScript.fsproj relative to /Users/chethusk/.vscode/extensions/georgewfraser.fsharp-language-server-0.1.3/src/FSharpLanguageServer/bin/Release/netcoreapp2.0/osx.10.11-x64/publish/ProjectCracker.dll
Build started 6/4/18 11:56:57 AM.
__________________________________________________
Project "/Users/chethusk/.vscode/extensions/georgewfraser.fsharp-language-server-0.1.3/client/PseudoScript.fsproj" (Compile target(s)):

Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target GetAssemblyVersion:
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: The "GetAssemblyVersion" task failed unexpectedly.
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: File name: 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GetAssemblyVersion.ExecuteCore()
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in E:\A\_work\82\s\src\Build\BackEnd\TaskExecutionHost\TaskExecutionHost.cs:line 631
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() in E:\A\_work\82\s\src\Build\BackEnd\Components\RequestBuilder\TaskBuilder.cs:line 787
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
    /usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
Done building target "GetAssemblyVersion" in project "PseudoScript.fsproj" -- FAILED.

Done building project "PseudoScript.fsproj" -- FAILED.

Build FAILED.

/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: The "GetAssemblyVersion" task failed unexpectedly.
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: File name: 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GetAssemblyVersion.ExecuteCore()
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in E:\A\_work\82\s\src\Build\BackEnd\TaskExecutionHost\TaskExecutionHost.cs:line 631
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() in E:\A\_work\82\s\src\Build\BackEnd\Components\RequestBuilder\TaskBuilder.cs:line 787
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.53
Exception in language server System.Exception: Failed to load PseudoScript.fsproj: Object reference not set to an instance of an object.
   at ProjectCracker.scriptBase@72.Invoke(Unit unitVar) in /Users/georgefraser/Documents/fsharp-language-server/src/ProjectCracker/ProjectCracker.fs:line 81
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FSharpLanguageServer.ProjectManager.analyzeFsx(FileInfo fsx) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/ProjectManager.fs:line 100
   at FSharpLanguageServer.ProjectManager.ensureAll(FSharpList`1 fs) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/ProjectManager.fs:line 178
   at <StartupCode$FSharpLanguageServer>.$ProjectManager.AddWorkspaceRoot@186.Invoke(Unit unitVar) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/ProjectManager.fs:line 189
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at LSP.LanguageServer.connect(FSharpFunc`2 serverFactory, BinaryReader receive, BinaryWriter send) in /Users/georgefraser/Documents/fsharp-language-server/src/LSP/LanguageServer.fs:line 213
   at FSharpLanguageServer.Program.main(String[] argv) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/Program.fs:line 703
```

**Comment by baronfel** [comment]
In addition, after I remove all fsx scripts from my project root and begin loading project files, every single one fails saying the target `Compile` doesn't exist in the project:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
    <Tailcalls>true</Tailcalls>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="DateTime.fs" />
    <Compile Include="Caching.fs" />
    <Compile Include="Retry.fs" />
    <Compile Include="Hopac.Actors.fs" />
    <Compile Include="SemVer.fs" />
    <Compile Include="UserAgentParser.fs" />
    <Compile Include="Logary.Utils.fs" />
    <Compile Include="Collection.fs" />
    <Compile Include="JsonConverters.fs" />
    <Compile Include="Json.fs" />
    <Compile Include="Hashing.fs" />
    <Compile Include="Uri.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

In my experience, this means that the project file isn't being  read by the correct msbuild, and/or the project isn't being restored correctly.

**Comment by georgewfraser** [comment]
I think these are both instances of the same problem, which is that the MSBuild on your system isn't doing what Buildalyzer expects. The language server follows a simple procedure to discover all projects in a workspace:
- Find all files ending in .fsproj or .fsx
- For .fsproj files:
  - Call [Buildalyzer](https://github.com/daveaglick/Buildalyzer) `Load()` and `Compile()`
    - Buildalyzer locates a copy of MSBuild on your system and sets several environment variables pointing to it
    - Buildalyzer then calls the [MSBuild API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.project?view=netframework-4.7), which uses these environment variables to find things like SDKs
  - Once the `Compile` target succeeds, we can inspect the project via the MSBuild API for source-files, project-references and package-references
- For .fsx files:
  - Call [FCS](https://github.com/fsharp/FSharp.Compiler.Service) GetProjectOptionsFromScript
  - Combine that with Buildalyzer results from `PseudoProject.fsproj`, an empty project that's packaged with the language server

I am wondering if the best solution to this class of problems would be to just package a copy of msbuild along with the language server, so that we're always using a predictable SDK. Do you have any thoughts about this @baronfel ?

**Comment by baronfel** [comment]
In my opinion the most portable thing would be to invoke msbuild out of process and have it dump project information, that way you use the dotnet/msbuild that the user will end up using as well when they invoke from build scripts or the col. This goes especially for cases where the user has a global.json in the repo for SDK pinning. Luckily, dotnet-proj-info does just this wink wink

**Comment by georgewfraser** [comment]
If you look at the history of this project, there was a period where I used dotnet-proj-info. However, I found several problems with it:
- It was no better at building "difficult" projects that Buildalyzer, for example it can't build FSharp Compiler Service.
- It's very slow, partly because it invokes MSBuild multiple times to inspect different aspects of the build.
- It's implementation is very opaque, so it's hard to use it for anything other than the exact intended purpose.

The way that Buildalyzer works is that it sets several environment variables pointing to an installation of MSBuild, and then calls the MSBuild API, which respects these environment variables. It seems to me we just need a function:

```fsharp
let locateAppropriateMsBuild(fsproj: FileInfo) = ???
```

and then MSBuild should work great. But I am definitely not an expert on msbuild, if you know there is a better strategy please convince me 😄

**Comment by jindraivanek** [comment]
With `dotnet` 2.1.300 I'm getting:

```
Listening on stdin
Add workspace root c:\dev\fsharp\SaturnSample
Creating project options for script build.fsx
Looking for PsuedoScript.fsproj relative to C:\Users\jivanek\.vscode\extensions\georgewfraser.fsharp-language-server-0.1.3\src\FSharpLanguageServer\bin\Release\netcoreapp2.0\win10-x64\publish\ProjectCracker.dll
Build started 05/06/2018 10:23:00.
__________________________________________________
Project "C:\Users\jivanek\.vscode\extensions\georgewfraser.fsharp-language-server-0.1.3\client\PseudoScript.fsproj" (Compile target(s)):

Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target GetAssemblyVersion:
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: The "GetAssemblyVersion" task failed unexpectedly.
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: File name: 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GetAssemblyVersion.ExecuteCore()
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in E:\A\_work\82\s\src\Build\BackEnd\TaskExecutionHost\TaskExecutionHost.cs:line 631
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() in E:\A\_work\82\s\src\Build\BackEnd\Components\RequestBuilder\TaskBuilder.cs:line 787
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
    C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
Done building target "GetAssemblyVersion" in project "PseudoScript.fsproj" -- FAILED.

Done building project "PseudoScript.fsproj" -- FAILED.

Build FAILED.

C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: The "GetAssemblyVersion" task failed unexpectedly.
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: File name: 'NuGet.Versioning, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GetAssemblyVersion.ExecuteCore()
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in E:\A\_work\82\s\src\Build\BackEnd\TaskExecutionHost\TaskExecutionHost.cs:line 631
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() in E:\A\_work\82\s\src\Build\BackEnd\Components\RequestBuilder\TaskBuilder.cs:line 787
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(161,5): error MSB4018: 
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.60
Exception in language server System.Exception: Failed to load PseudoScript.fsproj: Object reference not set to an instance of an object.
   at ProjectCracker.scriptBase@72.Invoke(Unit unitVar) in /Users/georgefraser/Documents/fsharp-language-server/src/ProjectCracker/ProjectCracker.fs:line 81
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FSharpLanguageServer.ProjectManager.analyzeFsx(FileInfo fsx) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/ProjectManager.fs:line 100
   at FSharpLanguageServer.ProjectManager.ensureAll(FSharpList`1 fs) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/ProjectManager.fs:line 178
   at <StartupCode$FSharpLanguageServer>.$ProjectManager.AddWorkspaceRoot@186.Invoke(Unit unitVar) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/ProjectManager.fs:line 189
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at LSP.LanguageServer.connect(FSharpFunc`2 serverFactory, BinaryReader receive, BinaryWriter send) in /Users/georgefraser/Documents/fsharp-language-server/src/LSP/LanguageServer.fs:line 213
   at FSharpLanguageServer.Program.main(String[] argv) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/Program.fs:line 703
```

If I create `global.json` with 2.1.4 version in `PseudoScript.fsproj` dir, it works.

**Comment by georgewfraser** [comment]
@baronfel @jindraivanek OK, I have just published a new version that uses a new strategy for cracking projects, which I think will be much more robust. It works like this:
- Invoke MSBuild using Buildalyzer, but *only use it to get information about .fs sources*
- Look for `project.assets.json`, and use it to figure out package references

This should be more robust to weird build scenarios, because `project.assets.json` is generated as part of the normal build process, not by the language server. So the user can do whatever insanity they want in their build process; as long as it generates project.assets.json, the editor will work.

It's going to take some more fiddling with the [parseProjectAssets](https://github.com/georgewfraser/fsharp-language-server/blob/master/src/ProjectCracker/ProjectCracker.fs) function to be able to handle all the corner cases, but I have tested it against several real-world projects and it's working pretty well. Please try the new version on your projects and let me know if it's working.

**Comment by georgewfraser** [comment]
Parsing `project.assets.json` for package references and `*.fsproj` for source references has proven to be a reliable strategy, I've tested this by opening a bunch of large, complex open-source F# projects and found that it works reliably. If any of you are finding you still can't open projects that you are able to build, please reopen the issue.
