### ISSUE TITLE
Errors with .fsx files

### ISSUE THREAD

**Issue by grishace** [georgewfraser/fsharp-language-server#29]
Tried to work with FAKE script.

![image](https://user-images.githubusercontent.com/8962463/48025273-2dd54000-e100-11e8-8dd9-def52a248aa0.png)

```
parameter: System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\Users\gbelenkiy\.vscode\extensions\georgewfraser.fsharp-language-server-0.1.18\src\FSharpLanguageServer\bin\Release\netcoreapp2.0\assembly'.
   at System.IO.Win32FileSystemEnumerableIterator`1.HandleError(Int32 errorCode, String path)
   at System.IO.Win32FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Win32FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Win32FileSystemEnumerableFactory.CreateFileNameIterator(String path, String originalUserPath, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Win32FileSystem.EnumeratePaths(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.EnumerateFileSystemNames(String path, String searchPattern, SearchOption searchOption, Boolean includeFiles, Boolean includeDirs)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.FSharp.Compiler.SimulatedMSBuildReferenceResolver.options@150.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Microsoft.FSharp.Compiler.SimulatedMSBuildReferenceResolver.SimulatedMSBuildResolver@29.Microsoft-FSharp-Compiler-ReferenceResolver-Resolver-Resolve(ResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String fsharpCoreDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, FSharpFunc`2 logMessage, FSharpFunc`2 logWarningOrError) (Code=SR001)
```

**Comment by georgewfraser** [comment]
It would be super helpful if you could make a minimal example that reproduces the problem.

**Comment by nilshelmig** [comment]
@georgewfraser 
I've got the problem by simply creating a `test.fsx` file

![test](https://user-images.githubusercontent.com/20659490/48140975-25206d80-e2aa-11e8-983b-69abff9099b9.PNG)

Output from "F# Language Server":
```
Autocompleting at d:\Repositories\test.fsx(2,1)
Finished typecheck, looking for completions...
Check failed, ignored 1 errors
Request 30 has already finished
Failed to create code lens because project options failed to load: [{range = {start = {line = 0;
                    character = 0;};
           end = {line = 0;
                  character = 1;};};
  severity = Some Error;
  code = None;
  source = None;
  message =
   "parameter: System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\Users\NHelmig\.vscode\extensions\georgewfraser.fsharp-language-server-0.1.18\src\FSharpLanguageServer\bin\Release\netcoreapp2.0\assembly'.
   at System.IO.Win32FileSystemEnumerableIterator`1.HandleError(Int32 errorCode, String path)
   at System.IO.Win32FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Win32FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Win32FileSystemEnumerableFactory.CreateFileNameIterator(String path, String originalUserPath, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Win32FileSystem.EnumeratePaths(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.EnumerateFileSystemNames(String path, String searchPattern, SearchOption searchOption, Boolean includeFiles, Boolean includeDirs)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.FSharp.Compiler.SimulatedMSBuildReferenceResolver.options@150.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Microsoft.FSharp.Compiler.SimulatedMSBuildReferenceResolver.SimulatedMSBuildResolver@29.Microsoft-FSharp-Compiler-ReferenceResolver-Resolver-Resolve(ResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String fsharpCoreDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, FSharpFunc`2 logMessage, FSharpFunc`2 logWarningOrError) (Code=SR001)";}]
Can't find symbols in test.fsx because of error in project options
Watched file d:\Repositories\test.fsx Changed
```

**Comment by ronaldschlenker** [comment]
Same Problem here. Creating the missing 'assembly' path seems to solve the issue.

**Comment by georgewfraser** [comment]
I think this is windows-specific so I am having trouble reproducing it. Assuming this is only affecting .fsx files, the root of the problem is probably in the function that infers compiler options for .fsx files:

https://github.com/georgewfraser/fsharp-language-server/blob/853ba305dd23c5580bb046645dff6262aa7637b2/src/FSharpLanguageServer/ProjectManager.fs#L239

It would help to figure this out if someone posted the *entire* log.

**Comment by ronaldschlenker** [comment]
Log is here:

[log.txt](https://github.com/georgewfraser/fsharp-language-server/files/2743460/log.txt)

If you have a look at the stack trace, you see that that there is a Problem inside here:

https://github.com/Microsoft/visualfsharp/blob/9b55eccd1bc83ed123c5ae08c577be5646861830/src/fsharp/SimulatedMSBuildReferenceResolver.fs#L141-L146

It seems that the internal SimulatedMSBuildReferenceResolver is assuming the existence of the mentioned and missing 'assembly' folder. Unfortunately, the stack trace ends there and I cannot see the original Code invoking it. Maybe it's the piece of Code you cited above.

Is there a way of Debugging the language Server? Maybe starting it out of VS with a Debugger attached and send a specific stdin to it?

**Comment by georgewfraser** [comment]
Yes you should be able to attach a debugger. You can change the command that is used to launch fsharp-language-server right here:

https://github.com/georgewfraser/fsharp-language-server/blob/58bc398291dcd141d88770c458ad75b4d97bcb3e/client/extension.ts#L21

Then hit F5 in vscode to run the extension out of your working directory. Then attach to the running process.

**Comment by ronaldschlenker** [comment]
I try starting with it today...

**Comment by georgewfraser** [comment]
The other option is to just add the missing path `src\FSharpLanguageServer\bin\Release\netcoreapp2.0\assembly` to the build. It's pretty klugey and I'm a little concerned it would be brittle, because we don't know *why* it works, but if @ronaldschlenker doesn't have success reproducing the problem I'm inclined to just do that.

**Comment by ronaldschlenker** [comment]
Finally, I am able to reproduce the issue in the Debugger, @georgewfraser.
The error comes from here:

https://github.com/georgewfraser/fsharp-language-server/blob/7ce8866f89651a3c7dd99400376fb9516712c85b/src/FSharpLanguageServer/ProjectManager.fs#L242

Next step is to create a project where I can isolate the issue. In the meanwhile, your suggested workaround seems reasonable to have a working build on Windows until the root cause is identified.

I continue working on it...

**Comment by georgewfraser** [comment]
Would someone on this thread please clean-install the latest version 0.1.22 and confirm that the workaround is effective?

**Comment by ronaldschlenker** [comment]
I can confirm it, executing the following steps (VSCode + Windows):

* Uninstall the Extension and close vscode
* Remove all **georgewfraser.fsharp-language-server-0.1.xxx** folders from the vscode extension folder
* Open vscode and reinstall

Result: 
* I can see that the **Assembly** Folder with the readme.md is present.
* There is no error in the Output and in the Editor, everything works fine.

**Comment by ronaldschlenker** [comment]
@georgewfraser I think I found the issue, and it's something that should be fixed inside FSharp.Compiler.Service.

I raised this issue: https://github.com/Microsoft/visualfsharp/issues/6161

I don't see a possibility this can be fixed here.

**Comment by georgewfraser** [comment]
Thanks @ronaldschlenker ! Hopefully the dumb workaround where we add the missing folder will fix this for now.
