### ISSUE TITLE
Extension stopped working in v0.1.21

### ISSUE THREAD

**Issue by ncave** [georgewfraser/fsharp-language-server#41]
Extension stopped working in v0.1.21 (and v0.1.22).
v0.1.20 still works like a champ (and is awesome).

Some details:
- .net Core: Version 2.2.102
- VS Code: Version: 1.30.2
- OS: Windows x64 10.0.14393

**Comment by georgewfraser** [comment]
Can you copy the output of "F# Compiler Service" log? See screenshot for how to get to it.

<img width="1193" alt="screen shot 2019-01-27 at 4 37 51 pm" src="https://user-images.githubusercontent.com/1369240/51809111-f3d48f80-2251-11e9-8dbf-f180c67397f4.png">

**Comment by ncave** [comment]
```
Listening on stdin
Add workspace root /c:/Projects/test-fs
Exception in language server System.NotSupportedException: The given path's format is not supported.
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at FSharpLanguageServer.Program.LSP-Types-ILanguageServer-Initialize@508.Invoke(Unit unitVar) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/Program.fs:line 508
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at LSP.LanguageServer.connect(FSharpFunc`2 serverFactory, BinaryReader receive, BinaryWriter send) in /Users/georgefraser/Documents/fsharp-language-server/src/LSP/LanguageServer.fs:line 223
   at FSharpLanguageServer.Program.main(String[] argv) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/Program.fs:line 842
```

**Comment by georgewfraser** [comment]
Could you please add this to .vscode/settings.json:

```json
{
    "fsharp.trace.server": "verbose"
}
```

and again copy you're log?

**Comment by georgewfraser** [comment]
(.vscode/settings.json is relative to the open project, not your home directory or anything like that)

**Comment by ncave** [comment]
sure, but from the error it looks like it's the leading slash in the path:
```
Add workspace root /c:/Projects/test-fs
Exception in language server System.NotSupportedException: The given path's format is not supported.
```

**Comment by georgewfraser** [comment]
Yes, but I need to figure out where in the JSON => Uri => File conversion things go wrong, and it doesn't reproduce on Mac or Linux

**Comment by ncave** [comment]
```
[Trace - 5:15:47 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 13380,
    "rootPath": "c:\\Projects\\test-fs",
    "rootUri": "file:///c%3A/Projects/test-fs",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ]
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            }
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/Projects/test-fs",
            "name": "test-fs"
        }
    ]
}


Listening on stdin
Add workspace root /c:/Projects/test-fs
Exception in language server System.NotSupportedException: The given path's format is not supported.
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at FSharpLanguageServer.Program.LSP-Types-ILanguageServer-Initialize@508.Invoke(Unit unitVar) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/Program.fs:line 508
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at LSP.LanguageServer.connect(FSharpFunc`2 serverFactory, BinaryReader receive, BinaryWriter send) in /Users/georgefraser/Documents/fsharp-language-server/src/LSP/LanguageServer.fs:line 223
   at FSharpLanguageServer.Program.main(String[] argv) in /Users/georgefraser/Documents/fsharp-language-server/src/FSharpLanguageServer/Program.fs:line 842

```

**Comment by georgewfraser** [comment]
Ugh, I'm pretty sure this is happening because I'm compiling everything AOT and it looks like System.Uri decides how to behave at compile-time rather than run-time:

https://referencesource.microsoft.com/#System/net/System/URI.cs,166

**Comment by ncave** [comment]
What about the extra slash [here](https://github.com/georgewfraser/fsharp-language-server/commit/cb973a1db3165574d531172abbf448b9c3c20dca#diff-7c087eb2c29a27dcede5921f1e98e31c)?

**Comment by georgewfraser** [comment]
That's a test file. Real file URIs always start with `file:///`

**Comment by georgewfraser** [comment]
@ncave would you please clone the latest master, run ./scripts/build.sh, restart VSCode, and tell me if this fixes it?

**Comment by ncave** [comment]
@georgewfraser Before I try building, could it be just the uri escaping [here](https://github.com/georgewfraser/fsharp-language-server/commit/cb973a1db3165574d531172abbf448b9c3c20dca#diff-66f8d71007cb98de678e86a5534a7b5a)?
Looks like it's escaping the colon (see above):
```
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///c%3A/Projects/test-fs",
            "name": "test-fs"
        }
```

**Comment by georgewfraser** [comment]
Hmm, I think you are right, Uri(_) constructor specifies its input should be unescaped.

**Comment by georgewfraser** [comment]
Should be fixed by v0.1.23, which basically reverts cb973a1db3165574d531172abbf448b9c3c20dca

**Comment by georgewfraser** [comment]
@ncave Could you please update and confirm that the fix worked?

**Comment by ncave** [comment]
@georgewfraser Perhaps specifically unescape just the pound afterwards?
Anyway, v0.1.23 works, thanks a lot for fixing it.
